name: Generate Stats

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Generate Main GitHub Stats (like Vercel)
      - name: Generate GitHub Stats
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=nitinaswal&show_icons=true&theme=radical" -o github-stats.svg

      # Generate Top Languages (like Vercel)
      - name: Generate Languages Stats
        run: |
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=nitinaswal&layout=compact&theme=radical" -o top-langs.svg

      # Commit and push
      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg top-langs.svg
          git commit -m "Update GitHub stats cards" || echo "No changes to commit"
          git push
