name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Stats Card (like GitHub Stats)
      - name: Generate Stats Card
        uses: lowlighter/metrics@latest
        with:
          filename: stats-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories
          plugin_followup: yes
          plugin_stars: yes
          config_timezone: Asia/Kolkata

      # Languages Card (like Top Langs)
      - name: Generate Languages Card
        uses: lowlighter/metrics@latest
        with:
          filename: languages-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          config_timezone: Asia/Kolkata

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats-metrics.svg languages-metrics.svg
          git commit -m "Update GitHub metrics cards" || echo "No changes to commit"
          git push
