name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history for rebase

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: nitinaswal
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_followup: yes
          plugin_stars: yes
          repositories_affiliations: owner, collaborator
          repositories_forks: yes

      - name: Commit metrics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -f metrics.svg ]; then
            git add metrics.svg
            git commit -m "Update GitHub metrics" || echo "No changes to commit"
            git pull --rebase origin main
            git push
          else
            echo "⚠️ metrics.svg not found, skipping commit."
          fi
